server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088

spring:
    profiles:
      active: dev
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
    mvc:
      static-path-pattern: /static/**
    resources:
      static-locations: classpath:/static/

logging:
  config: classpath:config/log-back.xml