server:
  tomcat:
    uri-encoding: UTF-8
  port: 8088

spring:
    profiles:
      active: dev
    http:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
#    mvc:
#      static-path-pattern: /static/**
#    resources:
#      static-locations: classpath:/static/
    thymeleaf:
        #模板的模式，支持 HTML, XML TEXT JAVASCRIPT
        mode: HTML5
        #编码 可不用配置
        encoding: UTF-8
        #内容类别,可不用配置
        content-type: text/html
        #开发配置为false,避免修改模板还要重启服务器
        cache: false
        #配置模板路径，默认是templates，可以不用配置
        prefix: classpath:/templates
        suffix: .html
logging:
  config: classpath:config/log-back.xml